# Generated by Django 4.2.3 on 2023-07-31 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='julgamento',
            name='nota_final',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='julgamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
