# Generated by Django 4.2.3 on 2024-02-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_jurado_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoiadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=21)),
                ('foto', models.ImageField(null=True, upload_to='apoiadores/')),
            ],
        ),
        migrations.CreateModel(
            name='Organizadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=21)),
                ('foto', models.ImageField(null=True, upload_to='organizadores/')),
            ],
        ),
    ]
