# Generated by Django 4.2.3 on 2024-02-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_apoiadores_organizadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurado',
            name='usuario',
        ),
    ]
