# Generated by Django 4.2.3 on 2024-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_remove_julgamento_nota_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='julgamento',
            old_name='nota_criatidade',
            new_name='nota_criatividade',
        ),
    ]
