# Generated by Django 4.2.3 on 2024-03-04 13:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0007_remove_julgamento_participante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Julgamento_MakeYourSelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_estetica', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('nota_criatividade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('nota_performance', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('nota_sustentabilidade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='julgamentos_makeyourself', to=settings.AUTH_USER_MODEL)),
                ('participante_makeyourself', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='julgamentos_makeyourself', to='central.makeyourself')),
            ],
        ),
    ]
